//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automatiza {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ParametroSistema {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParametroSistema() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Automatiza.ParametroSistema", typeof(ParametroSistema).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C21:C62.
        /// </summary>
        internal static string CelulasAssistenAtendimento {
            get {
                return ResourceManager.GetString("CelulasAssistenAtendimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C13:C42.
        /// </summary>
        internal static string CelulasCaixa {
            get {
                return ResourceManager.GetString("CelulasCaixa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C14:C48.
        /// </summary>
        internal static string CelulasCaixaTesoureiro {
            get {
                return ResourceManager.GetString("CelulasCaixaTesoureiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C9:C13.
        /// </summary>
        internal static string CelulasCaixaXTesoureiro {
            get {
                return ResourceManager.GetString("CelulasCaixaXTesoureiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C14:C48.
        /// </summary>
        internal static string CelulasEstagiario {
            get {
                return ResourceManager.GetString("CelulasEstagiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C16:C60.
        /// </summary>
        internal static string CelulasGerenteAdministrativo {
            get {
                return ResourceManager.GetString("CelulasGerenteAdministrativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C24:C74.
        /// </summary>
        internal static string CelulasGerenteContas {
            get {
                return ResourceManager.GetString("CelulasGerenteContas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C14:C48.
        /// </summary>
        internal static string CelulasGerenteContasXGerentePA {
            get {
                return ResourceManager.GetString("CelulasGerenteContasXGerentePA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C25:C74.
        /// </summary>
        internal static string CelulasGerentePA {
            get {
                return ResourceManager.GetString("CelulasGerentePA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C8:C11.
        /// </summary>
        internal static string CelulasTesoureitoXGerenteAdm {
            get {
                return ResourceManager.GetString("CelulasTesoureitoXGerenteAdm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Z:\Suporte\- GESTÃO DE ACESSOS\Clayton\conceção\.
        /// </summary>
        internal static string PathPlanilhasBaseConcecao {
            get {
                return ResourceManager.GetString("PathPlanilhasBaseConcecao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Z:\Suporte\- GESTÃO DE ACESSOS\Clayton\Revogação\.
        /// </summary>
        internal static string PathPlanilhasBaseRevogacao {
            get {
                return ResourceManager.GetString("PathPlanilhasBaseRevogacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Z:\Suporte\- GESTÃO DE ACESSOS\CCS-grupos-fluxos\Concessão\.
        /// </summary>
        internal static string PathSaveSheet {
            get {
                return ResourceManager.GetString("PathSaveSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a https://cocred.webhook.office.com/webhookb2/4751af8d-bcd9-4825-9fc0-a902e542538a@7ec496a7-d14b-4f3b-a48c-8b7478b1e3e6/IncomingWebhook/83e006a7f9da4f40aee0d245a7bfaad3/5202d1a9-ced3-4964-8081-7d0305fcf7b8.
        /// </summary>
        internal static string Url_Webhook {
            get {
                return ResourceManager.GetString("Url_Webhook", resourceCulture);
            }
        }
    }
}
